version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - 80:8080
    restart: always
    depends_on:
      - node
      - db
  node:
    build: ./docker
    restart: always
    volumes:
      - ./app:/app
    command: [sh, -c, npm start]
  db:
    image: mysql:latest
    container_name: wwothlo-mysql
    volumes:
      - ./docker/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
